server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location /admin-ui/ {
        index index.html;
        try_files $uri /index.html;
    }

    location = / {
        return 301 /admin-ui/;
    }

     location /sysinfo/ {
            proxy_pass http://opencast-allinone-opencast-1:8080/sysinfo/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /info/ {
            proxy_pass http://opencast-allinone-opencast-1:8080/info/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /services/ {
            proxy_pass http://opencast-allinone-opencast-1:8080/services/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


    location /admin-ng/ {
        proxy_pass proxy_pass http://opencast-allinone-opencast-1:8080/admin-ng/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }

}
