name: Push Docker Image to Harbor

on:
  push:
    branches:
      - test_github_actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor registry
        uses: docker/login-action@v2
        with:
          registry: 172.28.129.15
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 172.28.129.15/my-project/admin-ui:latest
